### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by DongDem** [xmba15/face_recognition_survey#1]
Sorry. can you upload again the model?
This link is died https://www.dropbox.com/s/2r5tg6e7n95x9q3/model-r50-am-lfw.zip

**Comment by xmba15** [comment]
Hi. I am kinda busy this week. I will try to take a look and upload the model again this weekend.

**Comment by xmba15** [comment]
@DongDem I have updated the link to the models. I think you can try it now.
